In [61]:
import pandas as pd
from pathlib import Path
import json

In [49]:
main_folder = Path.cwd().parent

df = pd.read_excel(f"{main_folder}/data/excels/kurikulum-revisi-24-cleaned.xlsx")

In [7]:
df.head()

,kode_mata_kuliah,nama_mata_kuliah,SKS,semester,status,deskripsi,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 52,Unnamed: 53,Unnamed: 54,Unnamed: 55,Unnamed: 56,Unnamed: 57,Unnamed: 58,Unnamed: 59,Unnamed: 60,Unnamed: 61
0,TSK1624101,Teknologi Informasi,3.0,1.0,wajib,Mata kuliah ini merupakan mata kuliah yang ter...,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,TSK1624103,Kalkulus I,3.0,1.0,wajib,Mahasiswa melakukan analisis terkait topik fun...,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,TSK1624104,Fisika Dasar I,3.0,1.0,wajib,"Mata kuliah Fisika Dasar I membahas tentang, k...",NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,TSK1624105,Kimia,2.0,1.0,wajib,Mata kuliah ini mempelajari konsep-konsep kimi...,NaN,NaN,NaN,NaN,...,(Cloud Infrastructure),Kode Mata Kuliah,TSK1624515,SKS,2,Jaringan Syaraf Tiruan,Kode Mata Kuliah,TSK1624516,Deskripsi,Mata kuliah ini memberikan kemampuan untuk mem...
4,TSK1624106,Pemrograman Dasar,2.0,1.0,wajib,NONE,NaN,NaN,NaN,NaN,...,2,Deskripsi,Dalam matakuliah ini mahasiswa akan belajar ma...,"Jaringan Skala Besar, Keamanan dan Otomasi + P...",TSK1624615,SKS,Mata kuliah ini membekali mahasiswa tentang ar...,Kode Mata Kuliah,NaN,NaN

In [50]:
df = df.iloc[:, :6]

df.head()

,kode_mata_kuliah,nama_mata_kuliah,SKS,semester,status,deskripsi
0,TSK1624101,Teknologi Informasi,3.0,1.0,wajib,Mata kuliah ini merupakan mata kuliah yang ter...
1,TSK1624103,Kalkulus I,3.0,1.0,wajib,Mahasiswa melakukan analisis terkait topik fun...
2,TSK1624104,Fisika Dasar I,3.0,1.0,wajib,"Mata kuliah Fisika Dasar I membahas tentang, k..."
3,TSK1624105,Kimia,2.0,1.0,wajib,Mata kuliah ini mempelajari konsep-konsep kimi...
4,TSK1624106,Pemrograman Dasar,2.0,1.0,wajib,NONE

In [51]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 134 entries, 0 to 133
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   kode_mata_kuliah  103 non-null    object
 1   nama_mata_kuliah  96 non-null     object
 2   SKS               96 non-null     float64
 3   semester          96 non-null     float64
 4   status            96 non-null     object
 5   deskripsi         96 non-null     object
dtypes: float64(2), object(4)
memory usage: 6.4+ KB

In [29]:
df.isna().sum()

kode_mata_kuliah    31
nama_mata_kuliah    38
SKS                 38
semester            38
status              38
dtype: int64

In [53]:
df = df.dropna()

In [54]:
df['SKS'] = df['SKS'].astype(int)
df['semester'] = df['semester'].astype(int)

df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 96 entries, 0 to 95
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   kode_mata_kuliah  96 non-null     object
 1   nama_mata_kuliah  96 non-null     object
 2   SKS               96 non-null     int64
 3   semester          96 non-null     int64
 4   status            96 non-null     object
 5   deskripsi         96 non-null     object
dtypes: int64(2), object(4)
memory usage: 5.2+ KB

In [60]:
def data_kosong(kolom):
    return f"Data {kolom} belum tersedia"

dokumen = []

for _, row in df.iterrows():
    kode_matkul = row["kode_mata_kuliah"] if row["kode_mata_kuliah"] != "NONE" else data_kosong("kode mata kuliah")
    nama_matkul = row["nama_mata_kuliah"] if row["nama_mata_kuliah"] != "NONE" else data_kosong("nama mata kuliah")
    SKS = row["SKS"] if row["SKS"] != "NONE" else data_kosong("SKS")
    semester = row["semester"] if row["semester"] != "NONE" else data_kosong("semester")
    status = row["status"] if row["status"] != "NONE" else data_kosong("status")
    deskripsi = row["deskripsi"] if row["deskripsi"] != "NONE" else data_kosong("deskripsi")
    deskripsi_tersedia = True if row['deskripsi'] != "NONE" else False

    baris = f"Mata kuliah: {nama_matkul} \n Kode mata kuliah: {kode_matkul} \n Semester: {semester} \n Bobot: {SKS} SKS \n Jenis mata kuliah: {status} \n Deskripsi: {deskripsi}"
    teks = f"{nama_matkul} ({kode_matkul}) adalah mata kuliah semester {semester} di Program Studi Teknik Komputer dengan bobot {SKS} SKS. \n {baris}"

    meta = {
        "tipe": "detail_matkul_24_rev",
        "semester": semester,
        "kode_matkul": kode_matkul,
        "nama_matkul": nama_matkul,
        "sks": SKS,
        "jenis_matkul": status,
        "deskripsi_tersedia": deskripsi_tersedia
    }

    data_jadi = {
        "id" : f"matkul-{kode_matkul}",
        "text" : teks,
        "metadata" : meta
    }

    dokumen.append(data_jadi)

dokumen[:5]

[{'id': 'matkul-TSK1624101',
  'text': 'Teknologi Informasi (TSK1624101) adalah mata kuliah semester 1 di Program Studi Teknik Komputer dengan bobot 3 SKS. \n Mata kuliah: Teknologi Informasi \n Kode mata kuliah: TSK1624101 \n Semester: 1 \n Bobot: 3 SKS \n Jenis mata kuliah: wajib \n Deskripsi: Mata kuliah ini merupakan mata kuliah yang terintegrasi dengan kurikulum netacad cisco, yaitu IT essential.',
  'metadata': {'tipe': 'detail_matkul_24_rev',
   'semester': 1,
   'kode_matkul': 'TSK1624101',
   'nama_matkul': 'Teknologi Informasi',
   'sks': 3,
   'jenis_matkul': 'wajib',
   'deskripsi_tersedia': True}},
 {'id': 'matkul-TSK1624103',
  'text': 'Kalkulus I (TSK1624103) adalah mata kuliah semester 1 di Program Studi Teknik Komputer dengan bobot 3 SKS. \n Mata kuliah: Kalkulus I \n Kode mata kuliah: TSK1624103 \n Semester: 1 \n Bobot: 3 SKS \n Jenis mata kuliah: wajib \n Deskripsi: Mahasiswa melakukan analisis terkait topik fungsi, Limit, turunan, dan integral. Mahasiswa mampu berdiskusi secara aktif terhadap topik tersebut. Pembahasan kasus bisa diambil dari buku, jurnal, dan kasus yang dipublikasi di media (Case method pada TM 3,5, 6,7,11,12,14,15).',
  'metadata': {'tipe': 'detail_matkul_24_rev',
   'semester': 1,
   'kode_matkul': 'TSK1624103',
   'nama_matkul': 'Kalkulus I',
   'sks': 3,
   'jenis_matkul': 'wajib',
   'deskripsi_tersedia': True}},
 {'id': 'matkul-TSK1624104',
  'text': 'Fisika Dasar I (TSK1624104) adalah mata kuliah semester 1 di Program Studi Teknik Komputer dengan bobot 3 SKS. \n Mata kuliah: Fisika Dasar I \n Kode mata kuliah: TSK1624104 \n Semester: 1 \n Bobot: 3 SKS \n Jenis mata kuliah: wajib \n Deskripsi: Mata kuliah Fisika Dasar I membahas tentang, kinematika, dinamika, usaha dan energi, sistem partikel, rotasi benda tegar, kesetimbangan, elastisitas dan patahan, fluida statis dan dinamis, getaran dan gelombang, temperatur, kalor dan hukum-hukum thermodinamika.',
  'metadata': {'tipe': 'detail_matkul_24_rev',
   'semester': 1,
   'kode_matkul': 'TSK1624104',
   'nama_matkul': 'Fisika Dasar I',
   'sks': 3,
   'jenis_matkul': 'wajib',
   'deskripsi_tersedia': True}},
 {'id': 'matkul-TSK1624105',
  'text': 'Kimia (TSK1624105) adalah mata kuliah semester 1 di Program Studi Teknik Komputer dengan bobot 2 SKS. \n Mata kuliah: Kimia \n Kode mata kuliah: TSK1624105 \n Semester: 1 \n Bobot: 2 SKS \n Jenis mata kuliah: wajib \n Deskripsi: Mata kuliah ini mempelajari konsep-konsep kimia secara menyeluruh terutama pada tingkat makroskopik dan mulai mengenalkan konsep kimia pada tingkat mikroskopik, serta aplikasi dan pengembangan kimia dalam berbagai bidang. Mahasiswa mempelajari tentang: konsep mol dan stoikiometri, tabel periodic dan sifat unsur, larutan & koloid, senyawa logam, senyawa karbon, katalis dan reaksi radikal, air dan pengolahannya, elektrokimia dan baterai, korosi, polimer dan polimer konduktif, semikonduktor, nanomaterial dan material pintar.',
  'metadata': {'tipe': 'detail_matkul_24_rev',
   'semester': 1,
   'kode_matkul': 'TSK1624105',
   'nama_matkul': 'Kimia',
   'sks': 2,
   'jenis_matkul': 'wajib',
   'deskripsi_tersedia': True}},
 {'id': 'matkul-TSK1624106',
  'text': 'Pemrograman Dasar (TSK1624106) adalah mata kuliah semester 1 di Program Studi Teknik Komputer dengan bobot 2 SKS. \n Mata kuliah: Pemrograman Dasar \n Kode mata kuliah: TSK1624106 \n Semester: 1 \n Bobot: 2 SKS \n Jenis mata kuliah: wajib \n Deskripsi: Data deskripsi belum tersedia',
  'metadata': {'tipe': 'detail_matkul_24_rev',
   'semester': 1,
   'kode_matkul': 'TSK1624106',
   'nama_matkul': 'Pemrograman Dasar',
   'sks': 2,
   'jenis_matkul': 'wajib',
   'deskripsi_tersedia': False}}]

In [62]:
with open(f"{main_folder}\data\jsonl\kurikulum-24-rev.jsonl", 'w', encoding='utf-8') as f:
    for d in dokumen:
        f.write(json.dumps(d, ensure_ascii=False) + "\n")

<>:1: SyntaxWarning: invalid escape sequence '\d'
<>:1: SyntaxWarning: invalid escape sequence '\d'
C:\Users\hppav\AppData\Local\Temp\ipykernel_54292\4243318742.py:1: SyntaxWarning: invalid escape sequence '\d'
  with open(f"{main_folder}\data\jsonl\kurikulum-24-rev.jsonl", 'w', encoding='utf-8') as f:

# **KURIKULUM 24**