In [41]:
import json
import pandas as pd
from pathlib import Path

In [30]:
main_folder = Path.cwd().parent

df = pd.read_excel(f"{main_folder}/data/excels/tenaga-pendidik-cleaned.xlsx")

df.head()

                                        NAMA                    JABATAN
0                  Erwan Yudi Indrasto, S.T.  Pengadministrasi Akademik
1  Charisma Tubagus Setyobudhi, B.Eng., M.T.       Teknisi Laboratorium
2                Fathia Fidiniari, A.Md.Kom.       Teknisi Laboratorium
3                        Bima Putra Prasetya       Teknisi Laboratorium
4                         Tri Susilo Witanto      Pengadministrasi Umum

In [31]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17 entries, 0 to 16
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   NAMA     17 non-null     object
 1   JABATAN  17 non-null     object
dtypes: object(2)
memory usage: 404.0+ bytes

In [32]:
standard_column = ['nama', 'jabatan']

df.columns = standard_column 

df.head()

                                        nama                    jabatan
0                  Erwan Yudi Indrasto, S.T.  Pengadministrasi Akademik
1  Charisma Tubagus Setyobudhi, B.Eng., M.T.       Teknisi Laboratorium
2                Fathia Fidiniari, A.Md.Kom.       Teknisi Laboratorium
3                        Bima Putra Prasetya       Teknisi Laboratorium
4                         Tri Susilo Witanto      Pengadministrasi Umum

In [34]:
gelar = ["Prof", "Dr", "Drs", "Dra", "Ir"]

def hapus_gelar(nama):
    nama = nama.split(',')[0]
    nama = nama.split(' ')
    nama = [item for item in nama if item not in gelar]
    return ' '.join(nama)

In [19]:
def ubah_format_nama(nama):
    return nama.title()

In [20]:
def slug(nama):
    slug = nama.lower().split(' ')
    return '-'.join(slug)

slug(sampel)

'bima-putra-prasetya'

In [39]:
dokumen = []
prodi = 'Teknik Komputer'

for idx, row in df.iterrows():
    nama = ubah_format_nama(row['nama'])
    nama_tanpa_gelar = hapus_gelar(ubah_format_nama(row['nama']))
    jabatan = row['jabatan']

    baris = f"Nama : {nama} \n Nama Tanpa Gelar : {nama_tanpa_gelar} \n Jabatan : {jabatan} "
    teks = f"{nama} adalah seorang tenaga pendidik yang memegang jabatan sebagai {jabatan}. \n\n {baris}"

    metadata = {
        "tipe" : "tenaga pendidik",
        "nama" : nama,
        "jabatan" : jabatan
    }

    dokumen.append({
        'id' : f"{idx}-tendik-{slug(nama_tanpa_gelar)}",
        'text' : teks,
        'metadata' : metadata
    })

In [42]:
with open(f"{main_folder}\data\jsonl\\tendik-tekkom.jsonl", 'w', encoding='utf-8') as f:
    for d in dokumen:
        f.write(json.dumps(d, ensure_ascii=False) + "\n")

<>:1: SyntaxWarning: invalid escape sequence '\d'
<>:1: SyntaxWarning: invalid escape sequence '\d'
C:\Users\hppav\AppData\Local\Temp\ipykernel_33396\623405393.py:1: SyntaxWarning: invalid escape sequence '\d'
  with open(f"{main_folder}\data\jsonl\\tendik-tekkom.jsonl", 'w', encoding='utf-8') as f: